config/routes.rb
Rails.application.routes.draw do
 root 'jobs#index'
  get    '/',  to: 'jobs#new'
    get    '/show',  to: 'jobs#show'
   post    '/create',  to: 'jobs#create'
 resources :jobs
 resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :jobs,optional: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs
  has_one_attached :image #look
  #accepts_nested_attributes_for :jobs
  validates :name, :company_statement,:logo,:url,:email, presence: true
  validates :email, format: {
      with: URI::MailTo::EMAIL_REGEXP,
      message: 'only valid allowed'
    }


end

app/models/job.rb
class Job < ApplicationRecord
  has_many :categories
  belongs_to :companies ,optional: true
  validates :title, :category_id,:jobtype,:headquarter,:region,:applylink,:description, presence: true
  validates :headquarter, length: { minimum: 3, maximum: 20 }
  validates :applylink, length: { minimum: 7}
  validates :description, length: { minimum: 20,
    too_long: "%{count} characters is the maximum allowed" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    @category=Category.all
     if params[:category_id]
      category=  Category.find(params[:category_id])
    
     end
   end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  skip_before_action :verify_authenticity_token, raise: false
  before_action :index_category

  def new
    @job = Job.new
    @company = Company.new
  end

  def show
  end

  def index
    @company = Company.all
    @job=Job.all.order(created_at: :desc)#.group(@category.name)#.count.map{ |k,v| k << v }#.map{ |k,v| [k.first,k.last,v.length]}
      #(:category_id)#.group_by{:title}#.include(:jobs)
      #  else
      #@category_id=Category.find_by(name: params[:category]).id
      #  @job=Job.where[category_id: @category_id].order(created_at: :desc)
      #  end
  end

  def create
      @job=Job.new(job_params)
      @job.save
      @company=Company.new(company_params)
      @company.job_id=@job.id
        if @company.save
          flash[:notice]="Job was successfully created"
          redirect_to jobs_path
        else
          render 'new'
          #  redirect_to new_job_path
        end
  end

  private

  def job_params
    params.permit(:title,:category_id,:jobtype,:headquarter,:region,:applylink,:description)
  end

  def company_params
    params.permit(:name,:company_statement,:logo,:url,:email,:company_description)
  end

  def index_category
    @category=Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/index.html.erb
<div class="ui container" align="center" style="padding-top: 20px">

  <div class="big ui orange animated fade button" tabindex="0" >
  <div class="visible content">Post a job</div>
  <div class="hidden content" >
    <%= link_to "Click in", new_job_path %>
  </div>
  </div>
</div>
    <% @category.each do |kategori|  %>
          <% @company.each do |komp| %>
            <% @job.each do |cat| %>
                <% if komp.job_id==cat.id %>
                    <% if cat.category_id==kategori.id %>
  <div class="ui form segment" style="padding-top: 20px">
    <div class="ui feed" >
      <div class="event">
        <div class="label">
         <img src="">
        </div>
        <div class="content">

          <div class=" summary">
              <%= komp.name %>
              <%= link_to cat.title, job_path(cat.id) %>
              <div class="date">
                <%= days=(Date.current-cat.created_at.to_date).to_i %> days ago
              </div>
          </div>
          <div class=" orange label">
          <b> Category : <%= kategori.name %></b>
          </div>
        </div>
      </div>
    </div>

  </div>
            <% end %>
        <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/jobs/new.html.erb
<% if @job.errors.any? & @company.errors.any? %>
<div class="ui form error">
  <div class="ui error message">
      The form contains <%= pluralize(@job.errors.count + @company.errors.count, "error") %>.
    <ul>
    <% @job.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    <% @company.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  </div>
<% end %>

<form class="ui form segment" name="newform" method="POST" align="center" action="/create" >
<div class="container" align="center">
  <h4 class="ui dividing header">Basic Information</h4>
  <div class=" ten wide field" >
    <label>Title</label>
      <div class=" field">
        <input type="text" name="title" placeholder="example 'Designer'">
      </div>
    </div>

    <div class="five wide field" >
      <label>Category</label>
      <div class="ui fluid search selection dropdown">
        <input type="hidden" name="category_id">
        <i class="dropdown icon"></i>
        <div class="default text" name="category_id">Select category</div>
        <div class="menu">
    <div class="item" data-value="1"><i></i>Design</div>
    <div class="item" data-value="2"><i></i>Programming</div>
    <div class="item" data-value="3"><i ></i>Customer Support</div>
    <div class="item" data-value="4"><i ></i>Copywritting</div>
    <div class="item" data-value="5"><i> </i>DevOps & SysAdmin</div>
    <div class="item" data-value="6"><i> </i>Sales & Marketing</div>
    <div class="item" data-value="7"><i> </i>Business & Management</div>
    <div class="item" data-value="8"><i ></i>Finance & Legal</div>
    <div class="item" data-value="9"><i> </i>Product</div>
    <div class="item" data-value="10"><i> </i>All other</div>
  </div>
       </div>
    </div>
    <div class="five wide field">
      <label>Job type</label>
      <select class="ui fluid dropdown" name="jobtype" placeholder="Select type">

        <option >Full time</option>
        <option  >Contract</option>

      </select>
    </div>


  <h4 class="ui dividing header">Location information</h4>


    <div class="five wide field">
      <label>Headquarter</label>
      <input type="text" name="headquarter"  placeholder="location of job">
    </div>
    <div class="five wide field">
      <label>Region</label>
      <div class="ui selection dropdown">
        <input type="hidden" name="region">
        <div class="default text">select region</div>
        <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item" data-value="hnk">
            HNK
          </div>
          <div class="item" data-value="zhk">
            ZHK
          </div>
          <div class="item" data-value="ks">
            KS
          </div>
          <div class="item" data-value="usk">
            USK
          </div>
          <div class="item" data-value="pk">
            PK
          </div>
          <div class="item" data-value="zdk">
            ZDK
          </div>
          <div class="item" data-value="bpk">
            BPK
          </div>
          <div class="item" data-value="tk">
            TK
          </div>
          <div class="item" data-value="sbk">
            SBK
          </div>
        </div>
      </div>
    </div>

   <h4 class="ui dividing header">Apply link</h4>
   <div class="ten wide field" >
       <div class="ui labeled input">
     <div class="ui label" >
       http://
     </div>
     <input type="text" name="applylink" placeholder="apply_link.com">
   </div>
  </div>
   <h4 class="ui dividing header">Description</h4>
  </br></br></br></br>

  <input id="x"  type="hidden" name="description">
   <trix-editor input="x"></trix-editor>

   <h4 class="ui dividing header">Company Information</h4>
   <div class=" twelve wide field" >
     <label>Name</label>
       <div class=" field">
         <input type="text" name="name" placeholder="example 'Wizard Health doo'">
       </div>
     </div>
     <div class=" twelve wide field" >
       <label>Company statement</label>
         <div class=" field">
           <input type="text" name="company_statement" placeholder="Enter company statement/vision">
         </div>
       </div>

   <h4 class="ui dividing header">Logo</h4>
       <div class="five wide field">
         <input type="file" name="logo" >

      </div>

       <h4 class="ui dividing header">Website</h4>
       <div class="ten wide field" >
           <div class="ui labeled input">
         <div class="ui label" >
           http://
         </div>
         <input type="text" name="url" placeholder="companysite.com">
       </div>
      </div>
      <div class=" ten wide field" >
        <label>Email</label>
          <div class=" field">
            <input type="text" name="email" placeholder="Example 'wizard@gmail.com'">
          </div>
        </div>
        <h4 class="ui dividing header">Details about company</h4>
       </br></br></br></br>
        <input id="x"  type="hidden" name="company_description">
         <trix-editor input="x"></trix-editor>
      <input type="submit" value="Submit" class="ui button" />
</div>
</form>

app/views/jobs/show.html.erb
<div class="ui container" align="center" style="padding-top: 20px">

 <h1> Ovo je za ispis o poslu </h1>

</div>

app/views/layouts/_categories.html.erb
<%= form_tag('/category',:method=>:get) do %>
<%= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "name") %>
 <%= submit_tag %>
<% end %>

app/views/layouts/_footer.html.erb
<footer >
  <div class='container' align="center">
  <div class="ui section divider"></div>

  <div class="ui container">
    JobBoard App. All Rights Reserved
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="ui grey one inverted  menu">
    <%= link_to "JobBoard", jobs_path, class: "item" %>

<div class="ui  dropdown">
  <input type="hidden" name="category_id">
  <div class="item" name="category_id">Categories</div>
  <div class="menu">
      <% @category.each do |cat| %>
          <%= link_to cat.name, root_path(cat.id), class: "item" %>
      <% end %>
  </div>
 </div>
  <div class="right menu">
    <div class="item">
      <div class="ui icon input">
        <input type="text" placeholder="Search...">
        <i class="search link icon"></i>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

 <div class="ui container">
     <%= render 'layouts/header' %>
  
      <%= yield %>
   <%= render 'layouts/footer' %>
 </div>

  </body>
</html>